### ISSUE TITLE
Unloadable MPQ - Possibly (hash table) decryption wrong

### ISSUE THREAD

**Issue by IceReaper** [Drake53/War3Net#13]
I currently have a wow-patch.mpq which is not properly loaded.
Viewing the hash table with Ladik's MPQ Editor shows the first entry should be mostly filled with 0xff.
War3Net displays some random (mis-decrypted?) values here.
Im quite unsure why and how it happens and trying to debug that somehow.
If im able find out the cause, ill comment on this issue about what i found out.

The file itself is the wow-patch.mpq from "wow-1.12.1.5875-to-1.12.2.6005-enGB-patch.zip" also sometimes named "wow-1.12.1-to-1.12.2-enGB-patch.zip", which can be downloaded for example from here: https://www.getmangos.eu/downloads/file/64-wow-1121-to-1122-dede-engb/

**Comment by Drake53** [comment]
Got it from a different source since the site you linked requires an account to download the file.
https://archive.org/download/World_of_Warcraft_Client_and_Installation_Archive/Patches/1.x/WoW-1.12.1-to-1.12.2-enGB-patch.zip

The mpq file version is 1, while this library only supports version 0.

The only reason you're not seeing an exception is because this library is for warcraft 3, which does not check the version, so as a form of protection some people set this version number to 1 or some other random number.
