### ISSUE TITLE
NuGet broken version

### ISSUE THREAD

**Issue by AzuStar** [Drake53/War3Net#15]
Can't build anything since 5.0.0 (take down from nuget unless it's fixed)
MapBuilder throws a lot of nulls.
Furthermore, there are no examples and documentation anywhere for this new Builder.
Internally, code is low standard, for example opening Map through Map.Open preinits arrays with player data, forces etc.
Init modifier needs to be removed in Map class because maps might be just for editing/exploring purposes and not contain required data of forces, players, tech etc.
Right now I have to override it like so for my needs.
```csharp
            map.Info.Players.Clear();
            map.Info.Players.AddRange(allplayers.ToArray());
```

LegacyMapBuilder onarchive event doesn't work.

MapBuilder.Build() throws null error.
Map.CompileScript() throws null error.

**Comment by Drake53** [comment]
Sorry about the lack of samples, I don't really have time to make any.

I suggest you take a look at [LegacyMapBuilder](https://github.com/Drake53/War3Net/blob/7375aac9396de57bc7653da4bb155198c6c17304/src/War3Net.Build/LegacyMapBuilder.cs) Build() method as example, since it uses the new MapBuilder under the hood. You can also see the OnArchiveBuilding event commented out there. I decided not to reimplement it since the LegacyMapBuilder is obsolete, and its use case (#6) should be a lot easier if you use the new MapBuilder directly.
Another example of how to use the new MapBuilder can be found [here](https://github.com/Orden4/WCSharp/blob/master/LauncherBuild/Program.cs).

Not sure where you're getting the nulls from. Are they NullReferenceExceptions or ArgumentNullExceptions? The former could be considered a bug. Either way would be nice if you could give some examples. Also, I recommend you enable the Nullable Reference Types feature if you haven't already.

I use 'get;init;' for lists because this is the easiest way to ensure that they can never be null. If I change it to `get;set;` I'd have to manually implement the get and set method, manually add the backing field, and throw ArgumentNull in the setter if the value is null. Not saying I won't change it though, since I agree it's annoying you can't assign a new list directly, just explaining why I designed it like this.

'Map.Open' opens the archive and parses all the war3map files to set the properties, not sure what else you would expect to happen here. I assume it's because of the above about 'get;init;', but if not please explain your use case.
