### ISSUE TITLE
War3Net.IO.Slk does not return last value in .slk files

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Net#16]

**Comment by Drake53** [comment]
As you mentioned in your PR, there were some off-by-one errors. I have made some additional changes to the documentation to hopefully prevent these kinds of errors.

I have rewritten the Combine method to use width/height instead of rows/columns, so it doesn't implicitly shrink the input tables anymore. In your test cases, one of the .slk files has its last column empty (which is why Width == 32 and Columns == 30, normally the difference is only 1). Due to this change some of the test cases in your PR no longer pass, but everything should work correctly now.

**Comment by YakaryBovine** [comment]
Excellent, thank you. That's good to know about the test cases; I did think a difference of 2 was odd.
