### ISSUE TITLE
6109 not defined Editor Version.

### ISSUE THREAD

**Issue by iJohnnis** [Drake53/War3Net#28]
While trying to open a frozen Throne Blizzard map ((4)iceforge.w3x), I am getting the following error:

System.IO.InvalidDataException: 'Value '6109' is not defined for enum of type EditorVersion.'

Reverting to version 5.4.2 fixed the error.
I am not sure if this is the right place to post it, given my limited experience with Github.

**Comment by Drake53** [comment]
This issue was introduced in v5.4.5: https://github.com/Drake53/War3Net/commit/253276799bb8a918a13ab81e39b711324e106473
Enum member value 6109 was added here: https://github.com/Drake53/War3Net/commit/1dcb8bd433f17dbc01429f91d0c0f3d45546101f
So it's already 'fixed', just haven't uploaded a new version yet.
Still wondering if i should just remove the validation though, because I changed the type from int to an enum, it now uses the extension method which automatically checks Enum.IsDefined, so I'd have to keep the values updated and some maps might also set it so some random value as map protection.
