### ISSUE TITLE
Zopfli Compression

### ISSUE THREAD

**Issue by KrayOristine** [Drake53/War3Net#48]
Can you add Zopfli compression? Zopfli has better compression ratio then zlib and it can output as a deflate or a zlib format (but in this case we use zlib output format). It should be an easy job to do, since it only compresses not both compress and decompress.

**Comment by Drake53** [comment]
I'm currently using DotNetZip for ZLib compression, I don't see this package supporting Zopfli, and I don't plan on adding another dependency or making my own implementation for this.

However, I have added an interface that allows you to implement this yourself: https://github.com/Drake53/War3Net/blob/vjass/src/War3Net.IO.Mpq/IMpqCompressor.cs

You can then pass your own implementation to the Compress method in the new MpqStreamUtils class: https://github.com/Drake53/War3Net/blob/vjass/src/War3Net.IO.Mpq/MpqStreamUtils.cs

Note that I don't expect to update the nuget packages in the near future, since I'm in the middle of a big rework.

**Comment by KrayOristine** [comment]
Ah, that is better than adding another dependency right now. This is already enough so i will close this issue.
